
vpd_mapping = {
    'vpd_serious_and_organised_crime_exploitation': "Involvement in serious and organised crime or exploitation",
    'vpd_stalking_and_harassment': "Subject to stalking or harassment",
    'vpd_suicide_concern': "Concerns about risk of suicide",
    'vpd_violence_used': "Violence has been used",
    'vpd_weapon_used__acra_only_': "Weapon has been used (ACRA only)",
    'vpd_bullying': "Subject to bullying",
    'vpd_child_at_locus': "Child present at the scene",
    'vpd_neglect': "Subject to neglect",
    'vpd_self_neglect': "Exhibiting self-neglect",
    'vpd_child_criminal_exploitation__cce_': "Child criminal exploitation (CCE)",
    'vpd_child_sexual_exploitation__cse_': "Child sexual exploitation (CSE)",
    'vpd_community_triage_service': "Referred to Community Triage Service",
    'vpd_distress_brief_intervention__dbi_': "Referred for Distress Brief Intervention (DBI)",
    'vpd_dsdas': "Domestic abuse referral (DSDAS)",
    'vpd_child_victim': "Child is a victim",
    'vpd_child_witnessed': "Child witnessed the incident",
    'vpd_female_genital_mutilation__fgm_': "Victim of Female Genital Mutilation (FGM)",
    'vpd_forced_marriage__fm_': "At risk of or subject to forced marriage",
    'vpd_gambling': "Gambling issues present",
    'vpd_honour_based_abuse__hba_': "Victim of honour-based abuse (HBA)",
    'vpd_human_trafficking': "Victim of human trafficking",
    'vpd_looked_after_accommodated_child__laac_': "Looked After or Accommodated Child (LAAC)",
    'vpd_missing_person': "Reported as a missing person",
    'vpd_online_child_sexual_abuse_and_exploitation__ocsae_': "Online child sexual abuse or exploitation (OCSAE)",
    'vpd_pregnancy__unborn_baby_': "Pregnancy or concern for unborn baby",
    'vpd_sexual_harm': "Victim of sexual harm",
    'vpd_elderly': "Elderly person involved or at risk",
    'vpd_attempted_suicide': "Attempted suicide",
    'vpd_financial': "Financial issues present",
    'vpd_sight_loss': "Sight loss or impairment",
    'vpd_physical_disability': "Physical disability",
    'vpd_psychological_harm': "Exposed to or at risk of psychological harm",
    'vpd_self_harm': "History or risk of self-harm",
    'vpd_isolation': "Social isolation",
    'vpd_hearing_loss': "Hearing loss or impairment",
    'vpd_alcohol_consumption': "Problematic alcohol consumption",
    'vpd_learning_disability': "Learning disability",
    'vpd_communication_needs': "Communication difficulties or needs",
    'vpd_mental_health_issues': "Mental health issues",
    'vpd_drug_consumption': "Problematic drug use",
    'vpd_other': "Other significant concern not listed",
    'vpd_radicalisation': "At risk of or involved in radicalisation"
}


risk_assessment_questions = {
            1: "Is there any identified risk of suicide?",
            2: "Is criminality suspected to be a factor in the disappearance?",
            3: "Is the Missing Person vulnerable due to age, infirmity or other similar factor?",
            4: "Are there any known adverse effects if prescribed medication is not available to the Missing Person?",
            5: "Does the Missing Person have dementia, medical or mental health conditions, physical illnesses or disabilities?",
            6: "Does the Missing Person have problems interacting safely with others when finding themselves in unfamiliar circumstances?",
            7: "Is there a dependency on drugs, alcohol, medication or other substances?",
            8: "Is the Missing Person on the Child Protection Register?",
            9: "Do the current/previous weather conditions present additional risk? Consider all circumstances including age and clothing.",
            10: "Are there family/relationship problems or recent history of family conflict and/or abuse?",
            11: "Is the Missing Person a victim or perpetrator of domestic violence?",
            12: "Is there an ongoing personal issue linked to racial, sexual, homophobic, the local community or any cultural issues?",
            13: "Was the Missing Person involved in a violent and/or hate crime incident prior to disappearance?",
            14: "Are there any school, college, university, employment or financial problems?",
            15: "Is forced marriage or honour based abuse an issue?",
            16: "Is the Missing Person the victim of sexual exploitation, human trafficking or prostitution? If so, is going missing likely to place the Missing Person at risk of considerable harm.",
            17: "Are the circumstances of going missing different from normal behaviour patterns?",
            18: "Is there any known reason for the Missing Person to go missing?",
            19: "Are there any indications that preparations have been made for absence?",
            20: "What was the Missing Person intending to do when last seen? Did they fail to complete their intentions?",
            21: "Has the Missing Person disappeared previously and were they exposed to harm on such occasions?",
            22: "Is the Missing Person a risk to others? And if so in what way?",
            23: "Are there other unlisted factors which the officer or supervisor considers relevant in the assessment of risk?",
            24: "Does the Missing Person have a mental health condition (excluding dementia)?",
            25: "Does this Missing Person have dementia or a specific progressive neurological disorder?"
        }
